<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.86
     Generated on:       8/29/2015 9:35 PM
     Generated by:        
     Organization:        
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2015
#>

			<# Module Name:     DMGitTest.psm1
			## 
			## Author:          David Muegge
			##
			## Purpose:         
			##																					
			## Requirements:    PowerShell Version 3
			## 										
			## History:
			##                  0.10 2013-03-01 - Initial Creation
			##                                  
			##                                                                             
			###################################################################################################>
				
			# Helper functions
				
			
			# Exported Functions
			
			function Get-DMGitTest{
			<#
				.Synopsis
					Test
			
				.Description
					Test
			
			#>
			[CmdletBinding()]
			Param()
			
			    Write-Host "DMGitTest"
			
			}
			
			
								
			
							