<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.86
     Generated on:       8/29/2015 5:47 PM
     Generated by:        
     Organization:        
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2015
#>

	<# Module Name:     DMTest01.psm1
	## 
	## Author:          David Muegge
	## Purpose:         
	##																					
	## Requirements:    PowerShell Version 3
	## 					
	##					
	## History:
	##                  0.10 2013-03-01 - Initial Creation
	##                                  
	##                                                                             
	###################################################################################################>
	
	
	# Helper functions
	
	
	
	# Exported Functions
	
	
	
	
	
	
	function Get-DBPublic{
	<#
	.Synopsis
	    
	
	.Description
	    
	     
	
	.Example
	    
	
	.Example
	    
	
	.Parameter path
	    
	
	.Parameter name
	    
	
	.Parameter create
	    
	
	.inputs
	    [string]
	
	.outputs
	    [string]
	
	.Notes
	    
	
	.Link
	
	
	#Requires -Version 4.0
	
	#>
	[CmdletBinding()]
	Param()
	
	    Get-ChildItem -Path C:\users\dmuegge\Dropbox\Public
	
	
	
	
	}
	
	
						
	
					